const products=[{id:1,name:"Dell Inspiron Laptop",category:"Laptop",price:500,icon:"💻"},{id:2,name:"HP Pavilion Laptop",category:"Laptop",price:600,icon:"💻"},{id:3,name:"Canon DSLR Camera",category:"Camera",price:800,icon:"📷"},{id:4,name:"Sony Mirrorless Camera",category:"Camera",price:1000,icon:"📸"},{id:5,name:"PlayStation 5",category:"Gaming",price:700,icon:"🎮"},{id:6,name:"Epson Projector",category:"Projector",price:900,icon:"📽️"},{id:7,name:"JBL Speaker",category:"Speaker",price:300,icon:"🔊"},{id:8,name:"Apple MacBook Air",category:"Laptop",price:1200,icon:"💻"}];

function renderProducts(list=products){const grid=document.getElementById("productGrid");if(!grid)return;grid.innerHTML=list.map(p=>`<div class="product-card"><div class="product-image">${p.icon}</div><h3>${p.name}</h3><p>₹${p.price} / day</p><a class="btn" href="product-details.html">View Details</a><button class="btn" onclick="addToCart(${p.id})">Add to Cart</button></div>`).join("")}
function searchProducts(){const q=document.getElementById("search").value.toLowerCase();renderProducts(products.filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)))}
function addToCart(id){const p=products.find(x=>x.id===id);localStorage.setItem("rentalProduct",JSON.stringify(p));alert(p.name+" added to rental cart!")}
function addProductToCart(){const p=products[0];localStorage.setItem("rentalProduct",JSON.stringify(p));alert(p.name+" added to rental cart!")}
function renderCart(){const box=document.getElementById("cartBox");if(!box)return;const p=JSON.parse(localStorage.getItem("rentalProduct"));if(!p){box.innerHTML="<h3>Your rental cart is empty.</h3><a class='btn' href='products.html'>Browse Products</a>";return}box.innerHTML=`<div class="cart-item"><div><h3>${p.icon} ${p.name}</h3><p>₹${p.price} / day</p></div><div><label>Days:</label><input id="days" type="number" value="3" min="1" onchange="updateTotal()"></div></div><hr><h2>Total: ₹<span id="total">${p.price*3}</span></h2><button class="btn" onclick="checkout()">Proceed to Checkout</button>`}
function updateTotal(){const p=JSON.parse(localStorage.getItem("rentalProduct"));const days=Number(document.getElementById("days").value)||1;document.getElementById("total").textContent=p.price*days}
function checkout(){if(!localStorage.getItem("rentalProduct"))return;alert("Checkout demo: connect this page to your Java/Spring Boot backend for real orders.");window.location.href="login.html"}
function login(e){e.preventDefault();alert("Login demo successful! Connect authentication to your backend.");window.location.href="my-rentals.html"}
function register(e){e.preventDefault();alert("Registration demo successful!");window.location.href="login.html"}
renderProducts();renderCart();